In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from numpy import unique
from numpy import where
from sklearn.cluster import KMeans
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from numpy import genfromtxt
%cd /content/drive/My Drive/Colab Notebooks/
df = pd.read_csv(r'divar_posts_dataset.csv')

/content/drive/My Drive/Colab Notebooks


In [ ]:
df = pd.read_csv(r'divar_posts_dataset.csv')
df=df.iloc[0:10000]
df=df[['cat1','city','price']]
labelEncoder = LabelEncoder()
labelEncoder.fit(df['cat1'])
df['cat1'] = labelEncoder.transform(df['cat1'])
labelEncoder.fit(df['city'])
df['city'] = labelEncoder.transform(df['city'])

In [ ]:
x=df[['cat1','city']]
y=df['price']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20, random_state=27)
# print(x_train)
# print(y_train)
# print(x_test)
# print(y_test)

In [ ]:
SVC_model=SVC()
KNN_model=KNeighborsClassifier(n_neighbors=10)

In [ ]:
SVC_model.fit(x_train,y_train)
KNN_model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [ ]:
SVC_prediction=SVC_model.predict(x_test)
KNN_prediction=KNN_model.predict(x_test)

In [ ]:
print(accuracy_score(SVC_prediction, y_test))
print(accuracy_score(KNN_prediction, y_test))
print(confusion_matrix(SVC_prediction, y_test))
print(classification_report(KNN_prediction, y_test))

0.1685
0.1405
[[337   1   1 ...   1   1   1]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
              precision    recall  f1-score   support

          -1       0.77      0.18      0.30      1418
          18       0.00      0.00      0.00         0
         170       0.00      0.00      0.00         0
         400       0.00      0.00      0.00         0
         500       0.00      0.00      0.00         0
         800       0.00      0.00      0.00         0
        1000       0.00      0.00      0.00         0
        2000       0.00      0.00      0.00         0
        2500       0.00      0.00      0.00         0
        2580       0.00      0.00      0.00         0
        3000       0.00      0.00      0.00         0
        4000       0.00      0.00      0.00         0
        5000       0.00      0.00      0.00         0
        5800       0.00      0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
kmeans = KMeans(n_clusters=6) # You want cluster the passenger records into 2: Survived or Not survived
kmeans.fit(x_train)
KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
correct = 0
for i in range(len(x_train)):
    predict_me = np.array(x_train[i].astype(float))
    predict_me = predict_me.reshape(-1, len(predict_me))
    prediction = kmeans.predict(predict_me)
    if prediction[0] == y_train[i]:
        correct += 1
 
print(correct/len(x_train))


KeyError: ignored